### ISSUE TITLE
Host Key Verification Fails

### ISSUE THREAD

**Issue by of6** [olipo186/Git-Auto-Deploy#101] opened 2016-05-26 17:35 UTC
I've setup Git-Auto-Deploy from the PPA on a **remote server**.

This is a private repo so I'm using the ssh url in my config settings  git@github.com:GenericAccount/GenericRepo.com.git

I've added the remote server public key to the machine user's SSH keys and was able to successfully do a git clone of the repo.

But when I run git-auto-deploy it can't read the host key?

```
Listening on 0.0.0.0 port 8080
Incoming request from 192.30.252.41:52349  
Handling the request with GitHubRequestParser  
Received 'push' event from GitHub  
Push to branch 'refs/heads/master' was fired  
Event details - ref: refs/heads/master; action:  
Successfully obtained lock: /var/www/GenericRepo/status_running  
Updating repository /var/www/GenericRepo  
Host key verification failed.  
fatal: Could not read from remote repository.  
Please make sure you have the correct access rights and the repository exists.
```
I also tested this with a test public repo and get the same issue.

One thing to note is that every time I run ```sudo service git-auto-deploy start``` I get this notice
```
The authenticity of host 'github.com (192.30.252.121)' can't be established.
RSA key fingerprint is xx:xx:xx:xx:xx:xx:xx:xx:xx......
Are you sure you want to continue connecting (yes/no)? yes
```

**Comment by of6** [comment] 2016-05-26 19:06
So it seems I solved it. Since it creates a invisible user called `git-auto-deploy` I had to create a key in `/etc/git-auto-deploy/.ssh/`

Has anyone else run into this issue or had a different/better solution?

**Comment by codybuell** [comment] 2016-06-08 02:38
Had same errors showing up.  Had to also create the service accounts home dir and touch /etc/git-auto-deploy/.ssh/known_hosts.  Seems to be working fine now.

**Comment by rodolphopivetta** [comment] 2016-06-09 13:36
I have this problem here but yours solutions doesn't work for me.

I created the ssh-keygen in /etc/git-auto-deploy/.ssh folder

```
root@1b182a1984a7:/# ls /etc/git-auto-deploy/.ssh/
id_rsa  id_rsa.pub  known_hosts
```

But this is not working. Do you can give me more details about your solutions?

**Comment by rodolphopivetta** [comment] 2016-06-09 13:37
I'm getting in the log:

```
2016-06-09 13:31:51,858 [INFO ]  Incoming request from 192.168.2.22:45908
2016-06-09 13:31:51,858 [INFO ]  Handling the request with GitLabRequestParser
2016-06-09 13:31:51,858 [DEBUG]  Received 'Push Hook' event from GitLab
2016-06-09 13:31:51,859 [DEBUG]  Event details - ref: refs/heads/master; action: push
2016-06-09 13:31:51,859 [DEBUG]  Successfully obtained lock: /gitlab/infra/status_running
2016-06-09 13:31:51,859 [INFO ]  Updating repository /gitlab/infra
2016-06-09 13:31:51,899 [ERROR]  Host key verification failed.
2016-06-09 13:31:51,900 [ERROR]  fatal: Could not read from remote repository.
2016-06-09 13:31:51,900 [ERROR]  
2016-06-09 13:31:51,900 [ERROR]  Please make sure you have the correct access rights
2016-06-09 13:31:51,900 [ERROR]  and the repository exists.
2016-06-09 13:31:51,900 [ERROR]  Unable to update repository /gitlab/infra
2016-06-09 13:31:51,900 [INFO ]  Updating repository /gitlab/infra
2016-06-09 13:31:51,933 [ERROR]  Host key verification failed.
2016-06-09 13:31:51,934 [ERROR]  fatal: Could not read from remote repository.
2016-06-09 13:31:51,934 [ERROR]  
2016-06-09 13:31:51,934 [ERROR]  Please make sure you have the correct access rights
2016-06-09 13:31:51,934 [ERROR]  and the repository exists.
2016-06-09 13:31:51,934 [ERROR]  Unable to update repository /gitlab/infra
2016-06-09 13:31:51,934 [INFO ]  Updating repository /gitlab/infra
2016-06-09 13:31:51,969 [ERROR]  Host key verification failed.
2016-06-09 13:31:51,969 [ERROR]  fatal: Could not read from remote repository.
2016-06-09 13:31:51,969 [ERROR]  
2016-06-09 13:31:51,969 [ERROR]  Please make sure you have the correct access rights
2016-06-09 13:31:51,969 [ERROR]  and the repository exists.
2016-06-09 13:31:51,970 [ERROR]  Unable to update repository /gitlab/infra
2016-06-09 13:31:51,970 [INFO ]  Updating repository /gitlab/infra
2016-06-09 13:31:52,003 [ERROR]  Host key verification failed.
2016-06-09 13:31:52,004 [ERROR]  fatal: Could not read from remote repository.
2016-06-09 13:31:52,004 [ERROR]  
2016-06-09 13:31:52,004 [ERROR]  Please make sure you have the correct access rights
2016-06-09 13:31:52,004 [ERROR]  and the repository exists.
2016-06-09 13:31:52,004 [ERROR]  Unable to update repository /gitlab/infra
2016-06-09 13:31:52,005 [DEBUG]  Successfully released lock: /gitlab/infra/status_running
2016-06-09 13:31:52,005 [INFO ]  192.168.1.18 - "POST / HTTP/1.1" 200 -
```

**Comment by of6** [comment] 2016-06-09 16:54
@rodolphopivetta make sure to `chown -R git-auto-deploy:git-auto-deploy /etc/git-auto-deploy/.ssh/`

**Comment by olipo186** [comment] 2016-06-09 17:25
I've added a few lines in the install script for debian (3bbafb1) to take care of the creation of the missing directories in the future.

@rodolphopivetta, did it work out after @of6 last suggestion?

**Comment by rodolphopivetta** [comment] 2016-06-09 17:42
It is not clear to me yet how the usar ```git-auto-deploy``` can execute git operations without a public key and what key I need to register in my project Deploy Keys

**Comment by codybuell** [comment] 2016-06-09 19:14
If you already have a deploy key generated put the private key in `/etc/git-auto-deploy/.ssh`.  My process with a fresh install from the apt repository:

- create `/etc/git-auto-deploy` directory
- generate ssh keys as root then move to `/etc/git-auto-deploy/.ssh`
- `touch /etc/git-auto-deploy/.ssh/known_hosts`
- `chown -R git-auto-deploy: /etc/git-auto-deploy`

**Comment by rodolphopivetta** [comment] 2016-06-13 19:43
I gave up of the installation, using the "clone" option it works fine in my case, thanks.

**Comment by antonioreyna** [comment] 2016-06-16 03:04
i have the same issue, i created the sshkey and moved to that file:

```
-rw------- 1 git-auto-deploy git-auto-deploy 1675 Jun 15 22:51 id_rsa
-rw------- 1 git-auto-deploy git-auto-deploy  408 Jun 15 22:51 id_rsa.pub
-rwxr-x--- 1 git-auto-deploy git-auto-deploy    0 Jun 15 21:14 known_hosts
```

what am i missing here?

**Comment by codybuell** [comment] 2016-06-17 15:38
So do a pull with the account that you created the keys with, accept the hosts signature, then copy the ~/.ssh/known_hosts file over to the git-auto-deploy ssh dir.

**Comment by olipo186** [comment] 2016-07-01 15:31
Closing this issue for now. Seems to be a lot of confusion regarding ssh keys, the ```git-auto-deploy``` user and the .ssh directory. Any suggestions on how to clarify this in the docs is much appreciated.

**Closed by olipo186** 2016-07-01 15:31 UTC

**Comment by Jossnaz** [comment] 2017-03-17 20:31
@olipo186 i have had same issue. And this is the second server I install your lib. I didn't have this problem on the first server. The problem is that for example when doing a fresh install on a server, all fresh, fresh fresh fresh,, the ssh key of say gitlab is not in the known hosts.  Now the clone doesn't work.

as a solution include @codybuell s solution. This worked for me:

do first a manual clone of the project with the user you use for ssh key -> manually accept the new host key
then, and only then, copy the ssh keys and known hosts file over to the git-auto-deploy folder.

**otherwise it wont work.**

**Comment by rodolphopivetta** [comment] 2017-03-17 22:47
A had again same issue past week and the problem described by @Jossnaz is exactly same i had, but I made a clone with git-auto-deploy user (`sudo -H -u git-auto-deploy bash -c "cd path/to/project && git clone ..."`).

**Comment by sweoggy** [comment] 2017-05-19 10:47
@rodolphopivetta Thanks, that worked great!

**Comment by amuzhyk** [comment] 2017-09-22 13:48
After manual generation known_hosts file it works

if [ ! -n "$(grep "^bitbucket.org " ~/.ssh/known_hosts)" ]; then ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts 2>/dev/null; fi
